//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Input/SphereInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @SphereInputAction : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @SphereInputAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""SphereInputAction"",
    ""maps"": [
        {
            ""name"": ""Sphere"",
            ""id"": ""15306cda-658b-4913-bd8e-6fa59f9dc85d"",
            ""actions"": [
                {
                    ""name"": ""Bounce"",
                    ""type"": ""Button"",
                    ""id"": ""ee5c9145-496c-448d-8300-6c9333333dac"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slider"",
                    ""type"": ""Button"",
                    ""id"": ""5f1fc4a0-3809-43cc-a1fc-c0f8211be1fe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""50b4f43b-0758-4107-b14a-14dacd5096c0"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": ""Hold(duration=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bounce"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8118eb7c-ebd5-4c5f-9f86-32492ff74ff4"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": ""Hold(duration=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slider"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Sphere
        m_Sphere = asset.FindActionMap("Sphere", throwIfNotFound: true);
        m_Sphere_Bounce = m_Sphere.FindAction("Bounce", throwIfNotFound: true);
        m_Sphere_Slider = m_Sphere.FindAction("Slider", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Sphere
    private readonly InputActionMap m_Sphere;
    private ISphereActions m_SphereActionsCallbackInterface;
    private readonly InputAction m_Sphere_Bounce;
    private readonly InputAction m_Sphere_Slider;
    public struct SphereActions
    {
        private @SphereInputAction m_Wrapper;
        public SphereActions(@SphereInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Bounce => m_Wrapper.m_Sphere_Bounce;
        public InputAction @Slider => m_Wrapper.m_Sphere_Slider;
        public InputActionMap Get() { return m_Wrapper.m_Sphere; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SphereActions set) { return set.Get(); }
        public void SetCallbacks(ISphereActions instance)
        {
            if (m_Wrapper.m_SphereActionsCallbackInterface != null)
            {
                @Bounce.started -= m_Wrapper.m_SphereActionsCallbackInterface.OnBounce;
                @Bounce.performed -= m_Wrapper.m_SphereActionsCallbackInterface.OnBounce;
                @Bounce.canceled -= m_Wrapper.m_SphereActionsCallbackInterface.OnBounce;
                @Slider.started -= m_Wrapper.m_SphereActionsCallbackInterface.OnSlider;
                @Slider.performed -= m_Wrapper.m_SphereActionsCallbackInterface.OnSlider;
                @Slider.canceled -= m_Wrapper.m_SphereActionsCallbackInterface.OnSlider;
            }
            m_Wrapper.m_SphereActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Bounce.started += instance.OnBounce;
                @Bounce.performed += instance.OnBounce;
                @Bounce.canceled += instance.OnBounce;
                @Slider.started += instance.OnSlider;
                @Slider.performed += instance.OnSlider;
                @Slider.canceled += instance.OnSlider;
            }
        }
    }
    public SphereActions @Sphere => new SphereActions(this);
    public interface ISphereActions
    {
        void OnBounce(InputAction.CallbackContext context);
        void OnSlider(InputAction.CallbackContext context);
    }
}
